### ISSUE TITLE
Inserting FNC1 into GS1-128

### ISSUE THREAD

**Issue by timothyjoelwright** [DavBfr/dart_barcode#13]
When creating USPS tracking barcodes using the GS1-128 format, how do I go about adding FNC1 in the correct position in the middle of the data? In a javascript library I'm migrating from, I would provide:

`(420)10030(92001901755477000226559615)` 

Which seems to place FNC1 at each open parenthesis. This is the correct barcode for this example:
![Screen Shot 2020-06-10 at 7 25 13 PM](https://user-images.githubusercontent.com/382693/84338121-1e29a300-ab50-11ea-89b0-a73a18f99b18.png)

An explanation of the format:
![impb-example](https://user-images.githubusercontent.com/382693/84338069-fcc8b700-ab4f-11ea-9dd7-835855a7da60.png)

**Comment by DavBfr** [comment]
What js library is it? I can implement the same kind of thing.

**Comment by timothyjoelwright** [comment]
Thank you for considering it! The library is bwip-js:
https://github.com/metafloor/bwip-js

**Comment by DavBfr** [comment]
Please test the master branch using this in your pubspec.yaml:

```yaml
dependency_overrides:
  barcode:
    git:
      url: git://github.com/DavBfr/dart_barcode
      path: barcode
```
