### ISSUE TITLE
dose the plugin support ITF16

### ISSUE THREAD

**Issue by kw2019ltd** [DavBfr/dart_barcode#24]
hi,
dose the plugin support ITF16 ?  

![image](https://user-images.githubusercontent.com/47334522/107779707-6b4cbd00-6d4e-11eb-9ab7-8048a2e34619.png)

![image](https://user-images.githubusercontent.com/47334522/107779749-77d11580-6d4e-11eb-965e-b6b94b48a0e8.png)

**Comment by DavBfr** [comment]
I don't have this one. Do you have some documentation?

**Comment by kw2019ltd** [comment]
> 
> 
> I don't have this one. Do you have some documentation?

hi could not find exactly it seems less popular , i found below it seems its similar to ITF14 only it support 16 digit.

https://docs.esko.com/docs/en-us/dynamicbarcodes-for-ai/12/userguide/en-us/common/bar/reference/re_bar_ITF-16.html
https://www.han-soft.com/releases/barcode1d/documents/b_itf16.html

someone from UK send me attached image above and wrote to me : " ITF 16 is popular with amazon return labels which will see an increase in use"

if you can somehow add it and its not complex will be good.

**Comment by DavBfr** [comment]
It's implemented in the master branch.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by kw2019ltd** [comment]
> 
> 
> It's implemented in the master branch.
> Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

sure thank you, i see build is failing can you have a look?

**Comment by DavBfr** [comment]
It's working now.

**Comment by kw2019ltd** [comment]
> 
> 
> It's working now.

thanks can you release new version? or you want me to tested first?

**Comment by DavBfr** [comment]
Yes, if you can test it first, that would be awesome.

In your pubspec.yaml, set:

```yaml
dependency_overrides:
  barcode:
    git:
      url: https://github.com/DavBfr/dart_barcode
      path: barcode
  barcode_widget:
    git:
      url: https://github.com/DavBfr/dart_barcode
      path: flutter
```

You'll need Flutter dev channel.
